### PR TITLE
Increase porechop stringency

### PR DESCRIPTION
**Pull request by alliblk**
Merging this branch with master fixes a major issue with the stringency of demultiplexing that Porechop conducts. Previously, Porechop did not use two barcodes to bin reads, which meant that there was a low-level, but influential, amount of read mixture. This made it appear as though negative controls had reads in them, and also made low levels of reads across barcodes get sorted into distinct barcode bins. The addition of the two barcode flag fixes this issue, and has been tested. 

This branch also features some new additions to the pipeline, including extending the pipeline to handle 12-plex runs as well, whereby samples have only one barcode/fasta, rather than two.

When this branch gets merged in, we should update the pipeline version.

### CODE REVIEW

**Comment by trvrb** [comment]
@barneypotter24 / @alliblk ---

What's going on with this PR? Should it be merged? I see further development happening on `master`. Are current Zika Colombia / Zika USVI analysis happening on data that was processed with `increase-porechop-stringency`? If so, this should certainly be merged.

**Comment by alliblk** [comment]
@trvrb Yes, this branch should definitely be merged in to master, as this increased stringency is what was used for calling the Colombian and USVI genomes used in the published analyses. @barneypotter24 I had you flagged to review it since you were the main developer on the pipeline, but if there's no conflicts maybe we should just merge now?

**Comment by barneypotter24** [comment]
I think this should be okay to just merge, especially if this has been working for Colobbian genomes and it doesn't look like there are any conflicts with master.

**Comment by barneypotter24** [comment]
Yes, these changes seem to make sense. Thanks for pushing this forward @alliblk.

**Pull request merged**
